# Generated by DoScript Visual IDE
# PortablePython Installer

# Script Start
say "=== PortablePython Installer ==="

global_variable = confirm

ask confirm "Would you like to install PortablePython? (y/n)"

if confirm == "y"
    say "Installing..."

    # Create install folder
    make folder "C:/PortablePython"

    # Download archive
    download "https://github.com/oskaritimperi/portablepython/archive/refs/heads/master.zip" to "C:/PortablePython/portablepython.zip"

    # Extract files
    unzip "C:/PortablePython/portablepython.zip" to "C:/PortablePython"

    # Optional: add python to PATH
    path add "C:/PortablePython/portablepython-master"

    # Remove zip after extraction
    delete "C:/PortablePython/portablepython.zip"

    say "Installation complete!"
end_if

pause
